spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC
    username: root
    password: uTu!LMwY+.^%VHVY5JwD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/dbchangelog.xml
    enabled: true
jwtSigningKey: 4E635266556A586E327234753778214125442A472D4B6150645367566B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A25432646
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
